# Generated by Django 6.1.1 on 2026-10-02 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('new_drive', 'New drive'), ('deadline', 'Registration deadline'), ('drive_date', 'Drive date reminder'), ('eligibility', 'Eligibility update'), ('preparation', 'Preparation reminder'), ('experience', 'New previous-drive experience'), ('offer_warning', 'Offer-term warning'), ('system', 'System')], default='system', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_drive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drives.placementdrive')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
