# Generated by Django 6.1.1 on 2026-10-02 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('logo_url', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, help_text='e.g. Product, Service, Startup', max_length=50)),
                ('products_services', models.TextField(blank=True)),
                ('company_size', models.CharField(blank=True, help_text='Approximate, e.g. 10,000+', max_length=60)),
                ('locations', models.CharField(blank=True, help_text='Comma separated', max_length=300)),
                ('careers_url', models.URLField(blank=True)),
                ('campus_hiring_info', models.TextField(blank=True)),
                ('typical_selection_process', models.TextField(blank=True)),
                ('ctc_information', models.TextField(blank=True)),
                ('important_requirements', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('category', models.CharField(choices=[('language', 'Programming language'), ('framework', 'Framework / library'), ('database', 'Database'), ('concept', 'CS concept'), ('tool', 'Tool'), ('other', 'Other')], default='other', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='companies.company')),
            ],
            options={
                'verbose_name_plural': 'company technologies',
            },
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='SavedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='companies.company')),
            ],
        ),
    ]
