# Generated by Django 6.1.1 on 2026-10-02 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcompany',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_companies', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='jobrole',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='roles', to='companies.skill'),
        ),
        migrations.AlterUniqueTogether(
            name='companytechnology',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='savedcompany',
            unique_together={('student', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='jobrole',
            unique_together={('company', 'title')},
        ),
    ]
