# Generated by Django 6.1.1 on 2026-10-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('selected', 'Selected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriveRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('round_type', models.CharField(choices=[('aptitude', 'Aptitude'), ('coding', 'Coding'), ('technical', 'Technical interview'), ('hr', 'HR interview'), ('gd', 'Group discussion'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('difficulty', models.PositiveSmallIntegerField(blank=True, help_text='1 easy, 2 medium, 3 hard; blank = unknown', null=True)),
            ],
            options={
                'ordering': ['drive', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Role title shown to students', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('drive_date', models.DateField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('registration_open', 'Registration Open'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('openings', models.PositiveIntegerField(blank=True, null=True)),
                ('min_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('max_backlogs', models.PositiveIntegerField(blank=True, null=True)),
                ('eligible_branches', models.CharField(blank=True, help_text='Comma separated; blank = all', max_length=300)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('ctc_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ctc_fixed', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ctc_variable', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('joining_bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('other_components', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bond_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('bond_penalty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notice_period_days', models.PositiveIntegerField(blank=True, null=True)),
                ('probation_months', models.PositiveIntegerField(blank=True, null=True)),
                ('relocation_required', models.BooleanField(blank=True, null=True)),
                ('training_agreement', models.BooleanField(blank=True, null=True)),
                ('terms_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['drive_date', '-created_at'],
            },
        ),
    ]
