# Generated by Django 6.1.1 on 2026-10-02 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
        ('drives', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='users.college'),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='companies.company'),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drives', to='companies.jobrole'),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='drives', to='companies.skill'),
        ),
        migrations.AddField(
            model_name='driveround',
            name='drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='drives.placementdrive'),
        ),
        migrations.AddField(
            model_name='application',
            name='drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='drives.placementdrive'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('student', 'drive')},
        ),
    ]
