# Generated by Django 6.1.1 on 2026-10-02 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField()),
                ('focus', models.CharField(blank=True, max_length=150)),
                ('area', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(max_length=250)),
                ('is_done', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['week', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PreparationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='drives.placementdrive')),
            ],
        ),
    ]
