# Generated by Django 6.1.1 on 2026-10-02 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preparation', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparationplan',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='preparationtask',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='preparation.preparationplan'),
        ),
        migrations.AlterUniqueTogether(
            name='preparationplan',
            unique_together={('student', 'drive')},
        ),
    ]
